# Copyright 2020-2026 Chemaxon Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  postgres:
    image: postgres:18
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  jms-config:
    image: chemaxon.jfrog.io/cxn-docker-release/chemaxon/jms-config:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_SERVER_KEY=${LICENSE_KEY}"
  jms-discovery:
    image: chemaxon.jfrog.io/cxn-docker-release/chemaxon/jms-discovery:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_SERVER_KEY=${LICENSE_KEY}"
    depends_on:
      - jms-config
  jms-db:
    image: chemaxon.jfrog.io/cxn-docker-release/chemaxon/jms-db:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_SERVER_KEY=${LICENSE_KEY}"
      - "CXN_DB_DIALECT=POSTGRESQL"
      - "CXN_DB_JDBC_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      - "CXN_DB_JDBC_USER=${POSTGRES_USER}"
      - "CXN_DB_JDBC_PASSWORD=${POSTGRES_PASSWORD}"
    depends_on:
      - jms-discovery
      - postgres
    deploy:
      mode: replicated
      replicas: 2
  jms-gateway:
    image: chemaxon.jfrog.io/cxn-docker-release/chemaxon/jms-gateway:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_SERVER_KEY=${LICENSE_KEY}"
    depends_on:
      - jms-discovery
    ports:
      - "8080:8080"

volumes:
  postgres-data:
