# Copyright 2020-2024 Chemaxon Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  license-server:
    image: cxn/jms/nginx-license-server
    build:
      context: ./
      dockerfile: nginx-license-server.dockerfile
  jms-config:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-config:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - license-server
  jms-discovery:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-discovery:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-config
  jms-calculations:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-calculations:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-db:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-db:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-io:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-io:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-markush:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-markush:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-reactor:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-reactor:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-structure:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-structure:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-structurechecker:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-structurechecker:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
    depends_on:
      - jms-discovery
  jms-gateway:
    image: hub.chemaxon.com/cxn-docker-release/chemaxon/jms-gateway:${JMS_VERSION}
    environment:
      - "EUREKA_URI=http://jms-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jms-config:8888/"
      - "CHEMAXON_LICENSE_URL=http://license-server/license.cxl"
      - "SERVER_SSL_KEY-STORE=/app/jws/${KEY_STORE_FILE}"
      - "SERVER_SSL_KEY-STORE-PASSWORD=${KEY_STORE_PASSWORD}"
      - "SERVER_SSL_KEYSTORETYPE=${KEY_STORE_TYPE}"
    depends_on:
      - jms-discovery
    volumes:
      - ./${KEY_STORE_FILE}:/app/jws/${KEY_STORE_FILE}
    ports:
      - "8080:8080"
